Done
lecrank/async pull request #1
Opened 2023-04-24 15:22 UTC by lecrank

2023-04-24 15:23 UTC, lecrank commented
Уровень вложенности в MultiHash...

2023-04-24 16:08 UTC, Yu-Leo requested changes
**Супер, очень круто!**

- Тесты проходят :fire:
- С точки зрения логики реализации всё верно
- Небольщие замечания, касающиеся оформления кода, прописал в комментариях

2023-04-24 16:08 UTC, Yu-Leo commented on signer/signer.go
> +}
Аналогично функции `SingleHash`.

Плюс в данном случае в каждой функции останется по одной waitgroup-е (которые можно будет назвать просто `wg`), что улучшит читаемость кода

2023-04-24 16:08 UTC, Yu-Leo commented on signer/signer.go
> +		resMultiHash := make([]string, 6)
В данном случае `6` - [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), которое к тому же повторяется несколько раз. Для лучшей читаемости рекомендую вынести в констнту с понятным именем (`NumberOfSteps`, например) и везде, где нужно, использовать её

2023-04-25 18:29 UTC, lecrank commented
ИСПРАВЛЕНО

2023-04-27 14:51 UTC, Yu-Leo approved these changes
**Вторая домашка принята! :fireworks:**

Всё, что прописал в комментариях, в целом уже необязательно и остаётся на твоё усмотрение. Если хочешь что-то исправить - исправь, если нет - можешь мерджить ветки

2023-04-27 14:51 UTC, Yu-Leo commented on signer/signer.go
> +const numberOfSteps int = 6
Не очень хорошо, что данная константа - глобальная. Лучше либо сделать её локальной (перенести в функцию `MultiHash`), либо оставить глобальной, но в названии отметить, что это кол-во этапов для вычисления MultiHash

2023-04-27 14:51 UTC, Yu-Leo commented on signer/signer.go
> +func countHalf(con chan<- string, n int, w *sync.WaitGroup, m *sync.Mutex) {
Мне кажется, лучше изменить сигнатуру данной функции так, чтобы она принимала на вход число (либо строку) и возращала тоже строку, а не писала результат в канал. На твоё усмотрение

2023-04-27 14:51 UTC, Yu-Leo commented on signer/signer.go
> +		dataConnector := make(chan string, 1)
Интересное решение (через вспомогательный канал).

Предложу альтернативное - возможно, оно тебе больше понравиться (актуально и для `SingleHash` и для `MultiHash`): можно создать слайс на n элементов (2 для SingleHash и 6 для MultiHash) и в вызываемые горутины передавать адреса элементов этого слайса, в которые они должны записать результаты своей работы. Примерный код (без wait-групп и прочего):

```go
func calculateMultiHash(data string) (result string) {
	output := make([]string, numberOfSteps)
	for i := 0; i < numberOfSteps; i++ {
		go multiHashOneStep(wg, strconv.Itoa(i)+data, &output[i])
	}
	result = strings.Join(output, "")
	return
}
``` 

Переделывать необязательно, это просто другой вариант реализации

2023-04-27 15:50 UTC, lecrank commented
Исправил имя константы, она используется несколькими функциями, поэтому оставил глобальной. Применил запись в массив по указателю, создал новую функцию. Теперь без мьютекса

2023-04-28 07:10 UTC, Yu-Leo commented
Хорошо. Если всё готово, можешь сливать ветки

2023-04-29 09:35 UTC, merged